### ISSUE TITLE
Unfollow users

### ISSUE THREAD

**Issue by whaner** [luiseduardobr1/InstagramAutomation#1]
É fácil criar um script para fazer o unfollow de usuários sem ter problemas com a API do Instagram?

**Comment by luiseduardobr1** [comment]
É sim. Eu fiz um teste dando "unfollow" nas pessoas que sigo mas que não me seguem de volta e notei que há um limite no instagram de 150 pessoas. Após isso, você fica impedido temporariamente de dar "unfollow". No dia seguinte já está normalizado de novo (talvez antes). 

Se você tiver o ID da conta do usuário basta usar:
```Python
api.friendships_destroy(ID_INSTAGRAM)
```

Se não souber o ID da conta, é possível encontrá-la com essa função simples sabendo apenas o "username":
```Python
import requests

def get_userID(username):
    response = requests.get('https://www.instagram.com/{}/?__a=1'.format(username))
    dictionary = json.loads(response.text)
    return(dictionary['graphql']['user']['id'])

print(get_userID('edux21'))
```

**Comment by whaner** [comment]
Valeu, vou testar.
